import { RouteInfo } from "./vertical-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/dash/web-sites",
    title: "Sitios webs",
    icon: "Layout",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dash/web-pages",
    title: "Páginas webs",
    icon: "Book",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "../../dash/sites/footers",
    title: "Footer",
    icon: "Layout",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "../../dash/sites/banner",
    title: "Banner",
    icon: "Layout",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "../../dash/sites/",
  //   title: "Sitio Web",
  //   icon: "Layout",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // }
  // {
  //   path: "/apps/tasks",
  //   title: "Tasks",
  //   icon: "Layout",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "../../../pages/static-page",
  //   title: "Páginas",
  //   icon: "Layout",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
];